### PR TITLE
Applying changes of bug fixes and optimizations

### PR DESCRIPTION
**Pull request by mister-svinia**
Changing the logging logic for connecting and disconnecting clients
Fixing errors related to multithreaded synchronization of expected clients' storage
Changing the logic of error handling when starting and stopping cores in main-function
Added Nullable/NotNull annotations to arguments and return values of DB-operators functions

Cleanup code

### CODE REVIEW

**Review by mister-svinia — COMMENTED** [review]
I confirm the changes.

**Review by AbsoluteCancer — COMMENTED** [review]
Checking the changes.

**Review by AbsoluteCancer — APPROVED** [review]
I confirm the changes.

**Comment by justanothercatgirl** [comment]
I confirm the changes

**Pull request merged**
